### ISSUE TITLE
fichier frank yo

### ISSUE THREAD

**Issue by fverella** [tipanverella/kiva-ayiti#1]
@tipanverella  pa bliye mete doc excel yo an parquet sou repository a

**Comment by tipanverella** [comment]
oke @fverella map eseye fe sa aswe a

**Comment by tipanverella** [comment]
Mwen pa jwenn fichye yo sou email mwen.  Eske ou ka voye li pou mwen sou whatsapp.

**Comment by fverella** [comment]
@tipanverella  mwen voye i pou ou pa email

**Comment by fverella** [comment]
Li long anpil wi 9test)
