### ISSUE TITLE
access a jupyterlab

### ISSUE THREAD

**Issue by fverella** [tipanverella/kiva-ayiti#4]
mwen al lan terminal la . Mwen fè control C apre y enter. Mwen jwenn prompt la (fanfan$) kan mwen ekri : make jupyterlab ou jupyter-lab. Li di m "no rule to make target 'jupyterlab'.

lot bagay mwen paka jwenn kote AyitiEDA.ipynb  OU UnibankEDA.ipynb yo ye

**Comment by tipanverella** [comment]
fok prompt lan ekri

`kiva-ayiti fanfan$`
